"Lista com os códigos dos relatórios"
# pylint: disable=E0401
# pylint: disable=C0303

COD_1 = "EVOLUCAO DAS VENDAS"
COD_3 = "VENDAS POR PROMOCAO"
COD_4 = "CUSTO MEDIO DE VENDAS"
COD_5 = "VENDAS POR MARGEM DE LUCRO"
COD_6 = "VENDAS POR PBM"
COD_7 = "VENDAS POR CARTAO"
COD_8 = "CANCELAMENTO DE VENDAS"
COD_9 = "VENDAS COM PRODUTOS DEVOLVIDOS"
COD_10 = "LISTAGEM DE VENDAS PRODUTOS CONTROLADOS E LOTES"
